%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_02.CSV
%
% Auto-generated by MATLAB on 02-Sep-2023 20:28:56

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Times", "Input", "Output_Displacement"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sin_002 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_02.CSV", opts);
sin_004 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_04.CSV", opts);
sin_006 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_06.CSV", opts);
sin_008 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_08.CSV", opts);
sin_010 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_10.CSV", opts);
sin_012 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_12.CSV", opts);
sin_014 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_14.CSV", opts);
sin_016 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_16.CSV", opts);
sin_018 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_18.CSV", opts);
sin_020 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_20.CSV", opts);
sin_022 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_22.CSV", opts);
sin_040 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_40.CSV", opts);
sin_100 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_100.CSV", opts);
sin_500 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_500.CSV", opts);
sin_1000 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_1000.CSV", opts);
sin_2000 = readtable("/home/bonga/Documents/EEE3094S/EEE3094S_Lab_01/recontrollab1rawdata/F34BSuspensionTestData_2000.CSV", opts);


%% Clear temporary variables
clear opts

%% Data processing of Frequency Response Test results performed on Simulated Spring-Mass Damper System

% Input sine wave frequency = 0.002 radian per second
time_002 = sin_002.Times;
input_002 = sin_002.Input;
output_002 = sin_002.Output_Displacement;

% Plot response of system to input 0.002 radian per second sine wave
time_002 = time_002(32:end); %start of test
input_002 = input_002(32:end);
output_002 = output_002(32:end) - 5;

plot(time_002,input_002);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.002 radian per second");
hold on
plot(time_002, output_002);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.002 rad per second

gain_002 = output_002./input_002;
gain_002_db = 20*log10(abs(gain_002));

sin_002_gain = table(time_002, input_002, gain_002_db);
plot(input_002, gain_002_db)

% Input sine wave frequency = 0.004 radian per second
time_004 = sin_004.Times;
input_004 = sin_004.Input;
output_004 = sin_004.Output_Displacement;

% Plot response of system to input 0.004 radian per second sine wave
time_004 = time_004(43:end); %start of test
input_004 = input_004(43:end);
output_004 = output_004(43:end) - 3.155;

plot(time_004,input_004);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.004 radian per second");
hold on
plot(time_004, output_004);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.004 rad per second

gain_004 = output_004./input_004;
gain_004_db = 20*log10(abs(gain_004));

sin_004_gain = table(time_004, input_004, gain_004_db);
plot(input_004, gain_004_db)

% Input sine wave frequency = 0.006 radian per second
time_006 = sin_006.Times;
input_006 = sin_006.Input;
output_006 = sin_006.Output_Displacement;

% Plot response of system to input 0.006 radian per second sine wave
time_006 = time_006(52:end); %start of test
input_006 = input_006(52:end);
output_006 = output_006(52:end) - 3.155;

plot(time_006,input_006);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.006 radian per second");
hold on
plot(time_006, output_006);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.006 rad per second

gain_006 = output_006./input_006;
gain_006_db = 20*log10(abs(gain_006));

sin_006_gain = table(time_006, input_006, gain_006_db);
plot(input_006, gain_006_db)

% Input sine wave frequency = 0.008 radian per second
time_008 = sin_008.Times;
input_008 = sin_008.Input;
output_008 = sin_008.Output_Displacement;

% Plot response of system to input 0.008 radian per second sine wave
time_008 = time_008(39:end); %start of test
input_008 = input_008(39:end);
output_008 = output_008(39:end) - 3.155;

plot(time_008,input_008);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.008 radian per second");
hold on
plot(time_008, output_008);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.008 rad per second

gain_008 = output_008./input_008;
gain_008_db = 20*log10(abs(gain_008));

sin_008_gain = table(time_008, input_008, gain_008_db);
plot(input_008, gain_008_db)

% Input sine wave frequency = 0.010 radian per second
time_010 = sin_010.Times;
input_010 = sin_010.Input;
output_010 = sin_010.Output_Displacement;

% Plot response of system to input 0.010 radian per second sine wave
time_010 = time_010(60:end); %start of test
input_010 = input_010(60:end);
output_010 = output_010(60:end) - 3.155;

plot(time_010,input_010);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.010 radian per second");
hold on
plot(time_010, output_010);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.010 rad per second

gain_010 = output_010./input_010;
gain_010_db = 20*log10(abs(gain_010));

sin_010_gain = table(time_010, input_010, gain_010_db);
plot(input_010, gain_010_db)

% Input sine wave frequency = 0.012 radian per second
time_012 = sin_012.Times;
input_012 = sin_012.Input;
output_012 = sin_012.Output_Displacement;

% Plot response of system to input 0.012 radian per second sine wave
time_012 = time_012(47:end); %start of test
input_012 = input_012(47:end);
output_012 = output_012(47:end) - 3.155;

plot(time_012,input_012);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.012 radian per second");
hold on
plot(time_012, output_012);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.012 rad per second

gain_012 = output_012./input_012;
gain_012_db = 20*log10(abs(gain_012));

sin_012_gain = table(time_012, input_012, gain_012_db);
plot(input_012, gain_012_db)

% Input sine wave frequency = 0.014 radian per second
time_014 = sin_014.Times;
input_014 = sin_014.Input;
output_014 = sin_014.Output_Displacement;

% Plot response of system to input 0.014 radian per second sine wave
time_014 = time_014(67:end); %start of test
input_014 = input_014(67:end);
output_014 = output_014(67:end) - 3.155;

plot(time_014,input_014);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.014 radian per second");
hold on
plot(time_014, output_014);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.014 rad per second

gain_014 = output_014./input_014;
gain_014_db = 20*log10(abs(gain_014));

sin_014_gain = table(time_014, input_014, gain_014_db);
plot(input_014, gain_014_db)

% Input sine wave frequency = 0.016 radian per second
time_016 = sin_016.Times;
input_016 = sin_016.Input;
output_016 = sin_016.Output_Displacement;

% Plot response of system to input 0.016 radian per second sine wave
time_016 = time_016(68:end); %start of test
input_016 = input_016(68:end);
output_016 = output_016(68:end) - 3.155;

plot(time_016,input_016);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.016 radian per second");
hold on
plot(time_016, output_016);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.016 rad per second

gain_016 = output_016./input_016;
gain_016_db = 20*log10(abs(gain_016));

sin_016_gain = table(time_016, input_016, gain_016_db);
plot(input_016, gain_016_db)

% Input sine wave frequency = 0.018 radian per second
time_018 = sin_018.Times;
input_018 = sin_018.Input;
output_018 = sin_018.Output_Displacement;

% Plot response of system to input 0.018 radian per second sine wave
time_018 = time_018(62:end); %start of test
input_018 = input_018(62:end);
output_018 = output_018(62:end) - 3.155;

plot(time_018,input_018);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.018 radian per second");
hold on
plot(time_018, output_018);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.018 rad per second

gain_018 = output_018./input_018;
gain_018_db = 20*log10(abs(gain_018));

sin_018_gain = table(time_018, input_018, gain_018_db);
plot(input_018, gain_018_db)

% Input sine wave frequency = 0.020 radian per second
time_020 = sin_020.Times;
input_020 = sin_020.Input;
output_020 = sin_020.Output_Displacement;

% Plot response of system to input 0.020 radian per second sine wave
time_020 = time_020(51:end); %start of test
input_020 = input_020(51:end);
output_020 = output_020(51:end) - 3.155;

plot(time_020,input_020);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.020 radian per second");
hold on
plot(time_020, output_020);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.020 rad per second

gain_020 = output_020./input_020;
gain_020_db = 20*log10(abs(gain_020));

sin_020_gain = table(time_020, input_020, gain_020_db);
plot(input_020, gain_020_db)

% Input sine wave frequency = 0.022 radian per second
time_022 = sin_022.Times;
input_022 = sin_022.Input;
output_022 = sin_022.Output_Displacement;

% Plot response of system to input 0.022 radian per second sine wave
time_022 = time_022(41:end); %start of test
input_022 = input_022(41:end);
output_022 = output_022(41:end) - 3.155;

plot(time_022,input_022);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.022 radian per second");
hold on
plot(time_022, output_022);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.022 rad per second

gain_022 = output_022./input_022;
gain_022_db = 20*log10(abs(gain_022));

sin_022_gain = table(time_022, input_022, gain_022_db);
plot(input_022, gain_022_db)

% Input sine wave frequency = 0.040 radian per second
time_040 = sin_040.Times;
input_040 = sin_040.Input;
output_040 = sin_040.Output_Displacement;

% Plot response of system to input 0.040 radian per second sine wave
time_040 = time_040(33:end); %start of test
input_040 = input_040(33:end);
output_040 = output_040(33:end) - 3.155;

plot(time_040,input_040);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.040 radian per second");
hold on
plot(time_040, output_040);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.040 rad per second

gain_040 = output_040./input_040;
gain_040_db = 20*log10(abs(gain_040));

sin_040_gain = table(time_040, input_040, gain_040_db);
plot(input_040, gain_040_db)

% Input sine wave frequency = 0.100 radian per second
time_100 = sin_100.Times;
input_100 = sin_100.Input;
output_100 = sin_100.Output_Displacement;

% Plot response of system to input 0.100 radian per second sine wave
time_100 = time_100(28:end); %start of test
input_100 = input_100(28:end);
output_100 = output_100(28:end) - 3.155;

plot(time_100,input_100);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.100 radian per second");
hold on
plot(time_100, output_100);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.100 rad per second

gain_100 = output_100./input_100;
gain_100_db = 20*log10(abs(gain_100));

sin_100_gain = table(time_100, input_100, gain_100_db);
plot(input_100, gain_100_db)

% Input sine wave frequency = 0.500 radian per second
time_500 = sin_500.Times;
input_500 = sin_500.Input;
output_500 = sin_500.Output_Displacement;

% Plot response of system to input 0.500 radian per second sine wave
time_500 = time_500(20:end); %start of test
input_500 = input_500(20:end);
output_500 = output_500(20:end) - 3.155;

plot(time_500,input_500);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 0.500 radian per second");
hold on
plot(time_500, output_500);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 0.500 rad per second

gain_500 = output_500./input_500;
gain_500_db = 20*log10(abs(gain_500));

sin_500_gain = table(time_500, input_500, gain_500_db);
plot(input_500, gain_500_db)

% Input sine wave frequency = 1.000 radian per second
time_1000 = sin_1000.Times;
input_1000 = sin_1000.Input;
output_1000 = sin_1000.Output_Displacement;

% Plot response of system to input 1.00 radian per second sine wave
time_1000 = time_1000(91:end); %start of test
input_1000 = input_1000(91:end);
output_1000 = output_1000(91:end) - 3.155;

plot(time_1000,input_1000);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 1.00 radian per second");
hold on
plot(time_1000, output_1000);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 1.00 rad per second

gain_1000 = output_1000./input_1000;
gain_1000_db = 20*log10(abs(gain_1000));

sin_1000_gain = table(time_1000, input_1000, gain_1000_db);
plot(input_1000, gain_1000_db);

% Input sine wave frequency = 2.000 radian per second
time_2000 = sin_2000.Times;
input_2000 = sin_2000.Input;
output_2000 = sin_2000.Output_Displacement;

% Plot response of system to input 2.00 radian per second sine wave
time_2000 = time_2000(21:end); %start of test
input_2000 = input_2000(21:end);
output_2000 = output_2000(21:end) - 3.155;

plot(time_2000,input_2000);
xlabel("Time (s)");
ylabel("Displacement (m)");
title("Sinusoidal of Spring-Mass Damper System At An Input Frequency of 2.00 radian per second");
hold on
plot(time_2000, output_2000);
hold off

% Calculate gain in decibel from the ratio of the output to the input for
% frequency of 2.00 rad per second

gain_2000 = output_2000./input_2000;
gain_2000_db = 20*log10(abs(gain_2000));

sin_2000_gain = table(time_2000, input_2000, gain_2000_db);
plot(input_2000, gain_2000_db);

%% Plot Bode Diagram

Frequency = [0.02; 0.04; 0.06; 0.08; 0.100; 0.120; 0.140; 0.160; 0.180; 0.200; 0.220; 0.400; 1.00; 5.00; 10.00; 20.00];
Frequency = log10(Frequency);
Gain = [7.875;7.875;7.875;7.875;7.875;7.875;7.871;7.871;7.871;7.868;7.864;7.825;7.318;4.695;4.399;3.33];
magnitude_table = table(Frequency, Gain);

magnitude_plot = plot(Frequency, Gain, 'LineWidth',2.5);
xlabel("Frequency (log\omega)");
ylabel("Gain (dB)");
title("Magnitude Spectrum For System Identification Using A Frequency Response Test");

% Add arrow pointing to cut-off frequency in Bode magnitude spectrum
txt = '\bullet \leftarrow \omega_n @ 2.21 rad/s';
text(Frequency(10),Gain(10),txt);
